### ISSUE TITLE
Add metadata endpoint to list all data bundle IDs and contents

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/dcc-storage#14]

**Comment by benjaminran** [comment]
https://ucsc-cgl.atlassian.net/wiki/display/DEV/Metadata+Id+Retrieval+-+Functional+Spec#

**Comment by briandoconnor** [comment]
From Bob at OICR:

"There is a way to dump a listing of all files:

https://github.com/icgc-dcc/dcc-storage/blob/develop/dcc-storage-server/src/main/java/org/icgc/dcc/storage/server/controller/ObjectListingController.java#L36 

but this does not return the gnos id:

https://github.com/icgc-dcc/dcc-storage/blob/develop/dcc-storage-core/src/main/java/org/icgc/dcc/storage/core/model/ObjectInfo.java

We use our dcc-metadata system for this, which is currently a private repo."

**Comment by briandoconnor** [comment]
I tried:

"curl -k -H 'access-token: ---' https://storage.ucsc-cgl.org:5431/listing
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}"

Didn't work... I think I'm not preparing the header properly here

**Comment by briandoconnor** [comment]
@benjaminran do you know how to do a direct curl to the storage URL?

**Comment by benjaminran** [comment]
I documented the correct command on the wiki (space system) this morning. You're missing an Authorization header. Unfortunately using this listing method would make us need to do an entire download of the storage system because no filenames are given

**Comment by benjaminran** [comment]
https://ucsc-cgl.atlassian.net/wiki/display/DEV/Storage+System+-+Developer+Notes#StorageSystem-DeveloperNotes-ExampleInteractionswithStorageSystem

**Comment by briandoconnor** [comment]
Thanks @benjaminran , so I hope all we have to do is modify the /listing endpoint to include filename… fingers crossed… Or does your research indicate that the filename doesn’t get tracked in the storage server, that’s why you suggested a new endpoint on the metadata server?
