### ISSUE TITLE
Multiple project scope support

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/dcc-storage#17]

**Comment by benjaminran** [comment]
https://ucsc-cgl.atlassian.net/wiki/display/DEV/Storage+Service+%28Redwood%29+-+Functional+Spec#StorageService(Redwood)-FunctionalSpec-Storage-ServerModificationForFiner-GrainedScope-BasedAuthorization

**Comment by benjaminran** [comment]
Proposing: Scopes (represented by strings) can reflect a hierarchy by making ancestor scopes be those that are prefixes of their child scopes, and authorizing users to access any objects whose corresponding scopes are children of a scope granted to the user. Details in link above. This will require modifying the metadata- and storage-server at least. To implement separate read/write permissions on each scope will likely require modifying the auth-server too.
